<?php
include_once('class.vCard.inc.php');
$vCard = (object) new vCard('','');

//$vCard->setFirstName('Max');
//$vCard->setMiddleName('Mobil');
//$vCard->setLastName('Mustermann');
//$vCard->setEducationTitle('Doctor');
//$vCard->setAddon('sen.');
//$vCard->setNickname('Maxi');
//$vCard->setCompany('NoBlood, Inc.');
$vCard->setOrganisation('NoBlood, Inc.');
//$vCard->setDepartment('Product Placement');
//$vCard->setJobTitle('CEO');
$vCard->setNote('A community of medical professionals and members of the public who are responding to the worldwide concern about the efficacy, cost and availability of donor blood.');
$vCard->setTelephoneWork1('(858) 866-9311');
//$vCard->setTelephoneWork2('+43 (05555) 000000');
//$vCard->setTelephoneHome1('+43 (05555) 000000');
//$vCard->setTelephoneHome2('+43 (05555) 000000');
//$vCard->setCellphone('+43 (05555) 000000');
//$vCard->setCarphone('+43 (05555) 000000');
//$vCard->setPager('+43 (05555) 000000');
//$vCard->setAdditionalTelephone('+43 (05555) 000000');
//$vCard->setFaxWork('+43 (05555) 000000');
//$vCard->setFaxHome('+43 (05555) 000000');
//$vCard->setISDN('+43 (05555) 000000');
//$vCard->setPreferredTelephone('(858) 866-9311');
//$vCard->setTelex('+43 (05555) 000000');
$vCard->setWorkStreet('3727 Christine Street');
$vCard->setWorkZIP('92117');
$vCard->setWorkCity('San Diego');
$vCard->setWorkRegion('CA');
$vCard->setWorkCountry('USA');
//$vCard->setHomeStreet('123 Examplestreet');
//$vCard->setHomeZIP('11111');
//$vCard->setHomeCity('Testcity');
//$vCard->setHomeRegion('PA');
//$vCard->setHomeCountry('USA');
//$vCard->setPostalStreet('123 Examplestreet');
//$vCard->setPostalZIP('11111');
//$vCard->setPostalCity('Testcity');
//$vCard->setPostalRegion('PA');
//$vCard->setPostalCountry('USA');
$vCard->setURLWork('http://www.noblood.org');
//$vCard->setRole('Student');
//$vCard->setBirthday(time());
$vCard->setEMail('info@noblood.org');
header('Content-Type: text/x-vcard');
header("Content-Disposition: attachment; filename=noblood.vcf");
echo $vCard->getCardOutput();