<?php
// Checksum file
// Product: crawlability_sitemap - vBSEO :: Sitemap Generator
// Version: 2.2
// File generated by: $RCSfile: mh_md5gen.php,v $ - $Revision: 2.0.0 $
// Generator: MD5 Version File generator by MarcoH64 and PitchouneN64ngc (c)

$md5_sums = array(
	'/vbseo_sitemap' => array(
		'index.php' => 'b5501cfdc3342e474b48c8a69016210c',
		'vbseo_getsitemap.php' => '93be8f245180a48b095ebceeee31329c',
		'vbseo_sitemap.php' => '8def9134952517f995906cc935e6fc0e',
		'vbseo_sitemap_config.php' => 'dc51af3fb3df6d0773e927475f2ad8bf',
		'vbseo_sitemap_functions.php' => '7a0efba7b861922dc4e7c81a1b082926',
		'vbseo_sm_config30x.php' => 'fe0751166665810668a4f48cb58251c8',
	),
	'/vbseo_sitemap/addons' => array(
		'vbseo_sm_downloads.php' => '97f77dc6599da0e79e4a123a64fbde8d',
		'vbseo_sm_downloads2.php' => '98a28e3a0da0d403a217a4c0615c456f',
		'vbseo_sm_vba.php' => '9874fa27ffd1e0594273e72233ef9a71',
		'vbseo_sm_vba_links.php' => 'd0c800a96b13269d8ddb7157971641eb',
	),
);
$md5_sum_softwareid = 'crawlability_sitemap';
$md5_sum_versions['crawlability_sitemap'] = '2.2';
?>
